CREATE TABLE IF NOT EXISTS notes(
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) UNIQUE,
	content TEXT NOT NULL,
	time_edited DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	favorite BOOLEAN DEFAULT FALSE,
	is_trashed BOOLEAN DEFAULT FALSE
);